### ISSUE TITLE
Failed compiling sheesy-cli v1.0.1

### ISSUE THREAD

**Issue by jverhoelen** [Byron/share-secrets-safely#1]
Hi,
just installed `rustup` and `cargo` to install sheesy-cli.
After executing `cargo install sheesy-cli`, I get a bunch of lines like `Compiling ...` which looks good.

Until:

```
Compiling libgpg-error-sys v0.3.1
Compiling gpgme-sys v0.7.0
Compiling gpgme v0.7.1
error: failed to run custom build command for `gpgme-sys v0.7.0`
process didn't exit successfully: `/var/folders/rg/jmhmvgl57rj4n1xmgyb2lt7m0000gn/T/cargo-install.MCN5Z2Gid1rP/release/build/gpgme-sys-69e4934ff7b01c8d/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-env-changed=GPGME_LIB_DIR
cargo:rerun-if-env-changed=GPGME_LIBS
cargo:rerun-if-env-changed=GPGME_CONFIG

--- stderr
running: "git" "apply" "../gpgme-remove-doc.patch"
error: patch failed: Makefile.am:33
error: Makefile.am: patch does not apply
error: patch failed: configure.ac:883
error: configure.ac: patch does not apply
command did not execute successfully, got: exit code: 1
running: "sh" "-c" "gpgme-config --version"
sh: gpgme-config: command not found
command did not execute successfully, got: exit code: 127

warning: build failed, waiting for other jobs to finish...
```

I'm running OSX El Capitan Version 10.11.6 (15G1510) if that helps somehow.

Do you have any idea if I can fix it myself?
Thanks in advance.

**Comment by Byron** [comment]
Thanks for trying it out!
For now I recommend using the precompiled binaries.
Otherwise you will have to install some dependencies, have a look at the
‘brew’ invocations in .travis.yml for the details.
I hope that helps.
Please note that v1 is an MVP, which will be completed soon when v2 is
released.
