### ISSUE TITLE
Feature Request: Please publish to home brew for OSX for easier adoption

### ISSUE THREAD

**Issue by sreedhap** [Byron/share-secrets-safely#2]

**Comment by Byron-TW** [comment]
I just spend a while to find a good document explaining how to do (and test it), and was surprisingly unsuccessful :D.
The best thing I could find is this: https://docs.brew.sh/Bottles.html, it seems like plenty of trial and error to get it to work.

**Comment by Byron** [comment]
I think `ripgrep` is exactly what this project should learn from: https://github.com/BurntSushi/ripgrep/blob/master/pkg/brew/ripgrep-bin.rb .

**Comment by sreedhap** [comment]
Awesome! Thank you. :-)
